name = "lptester"
main = "src/worker.ts"
compatibility_date = "2026-02-19"

# This tells Wrangler that this is a static site project
# and the build output directory is "dist".
[site]
bucket = "./dist"
